# Generated by Django 4.2.30 on 2026-08-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_professor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Aluno',
        ),
        migrations.AlterField(
            model_name='professor',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
